Test Rail Listener Changes
souravDgraph/Automation pull request #35
Opened 2021-02-05 06:59 UTC by kaushik691

Modified Common Lib and created CustomTestRailListener also added respective docs

2021-02-10 16:08 UTC, souravDgraph requested changes

2021-02-10 16:08 UTC, souravDgraph commented on lib/test_rail_listener_lib/CustomTestRailListener/components/test_rail_request.py
> +        :param project_id:
I see inconsistency some places \n is used. Some places it is not there.

2021-02-10 16:08 UTC, souravDgraph commented on lib/test_rail_listener_lib/CustomTestRailListener/components/test_rail_request.py
> +# pylint: disable=C0301
Why disabled??

2021-02-10 16:08 UTC, souravDgraph commented on lib/test_rail_listener_lib/CustomTestRailListener/components/test_rail_request.py
> +                This method expects an array of test results (via the 'results' field,
Why there are tabs in documentations, and some places it is not there.

2021-02-10 16:08 UTC, souravDgraph commented on lib/test_rail_listener_lib/CustomTestRailListener/keywords/CustomTestRailListener/custom_test_rail_listener.py
> +    OS = None
where is this used??

2021-02-11 06:37 UTC, kaushik691 commented on lib/test_rail_listener_lib/CustomTestRailListener/keywords/test_rail_keywords.py
> +# pylint: disable=C0301
line too long

2021-02-11 06:39 UTC, kaushik691 commented on lib/test_rail_listener_lib/CustomTestRailListener/components/test_rail_request.py
> +                This method expects an array of test results (via the 'results' field,
few i copied it from the inbuilt documentation

2021-02-11 06:41 UTC, kaushik691 commented on test_suites/sample_test_cases/sample_test_rails.robot
> +#    test rail add result for test case test run    ${run_id}   1496    status_id=2     version=20.11   comment=Updating Comments as part of Autamation comment
will make the change for username and password

2021-02-11 06:42 UTC, kaushik691 commented on lib/test_rail_listener_lib/setup.py
> +#####!/usr/bin/env python
# <-okay

2021-02-11 06:43 UTC, kaushik691 commented on lib/test_rail_listener_lib/CustomTestRailListener/keywords/test_rail_keywords.py
> +        \n:param run_id: 7
okay

2021-02-11 06:44 UTC, kaushik691 commented on lib/test_rail_listener_lib/CustomTestRailListener/keywords/CustomTestRailListener/custom_test_rail_listener.py
> +    OS = None
will change it

2021-02-11 07:15 UTC, kaushik691 commented on lib/test_rail_listener_lib/CustomTestRailListener/components/test_rail_request.py
> +# pylint: disable=C0301
line too long

2021-02-11 07:15 UTC, kaushik691 commented on lib/test_rail_listener_lib/CustomTestRailListener/keywords/CustomTestRailListener/custom_test_rail_listener.py
> +    OS = None
done

2021-02-11 07:16 UTC, kaushik691 commented on test_suites/sample_test_cases/sample_test_rails.robot
> +#    test rail add result for test case test run    ${run_id}   1496    status_id=2     version=20.11   comment=Updating Comments as part of Autamation comment
done

2021-02-11 07:16 UTC, kaushik691 commented on lib/test_rail_listener_lib/setup.py
> +#####!/usr/bin/env python
done

2021-02-11 07:17 UTC, kaushik691 commented on lib/test_rail_listener_lib/CustomTestRailListener/keywords/test_rail_keywords.py
> +        \n:param run_id: 7
done

2021-02-11 07:17 UTC, kaushik691 commented on lib/test_rail_listener_lib/CustomTestRailListener/components/test_rail_request.py
> +        :param project_id:
checked

2021-02-11 08:59 UTC, closed without merging