Added Security Test Cases For Slash API
souravDgraph/Automation pull request #44
Opened 2021-02-15 06:04 UTC by SanthoshS22

2021-02-17 08:48 UTC, vivetha-madesh commented on lib/slash_api_library/SlashAPI/components/handlers/organizations/organizations_handler.py
> +    def add_member(self, org_uid, member_email, expected_response=200, appender=None):
remove the existing add_member_to_organization and replace it with the current add_member method. 

Reason to make this change: We don't have unique organization names in Slash. 
Note: When going for the change make sure the test cases which were using add_member_to_organization are modified to use the upcoming approach

2021-02-17 08:48 UTC, vivetha-madesh commented on lib/slash_api_library/SlashAPI/keywords/organizations/organizations_keywords.py
> +            response = self.org_handler.add_member(org_uid, member_email)
rename this when u merge the add_member and add_member_to_organization

2021-02-17 08:48 UTC, vivetha-madesh commented on lib/slash_api_library/SlashAPI/keywords/organizations/organizations_keywords.py
> +            response = self.org_handler.add_member(org_uid, member_email,
rename this when u merge the add_member and add_member_to_organization

2021-02-17 08:48 UTC, vivetha-madesh commented on test_suites/slash/slash_api/security.robot
> +	${org_uid}=		Get Organization Uid		${org_name}
remove this and extract the organization uid from the response of create organization in all the places

2021-02-17 08:48 UTC, vivetha-madesh commented on test_suites/slash/slash_api/security.robot
> +	Create Session For Organization 	 ${AUTH_TOKEN}     https://api.thegaas.com
remove "https://api.thegaas.com" use the variable ${URL} from variables file

2021-02-18 07:23 UTC, souravDgraph requested changes

2021-02-18 07:23 UTC, souravDgraph commented on test_suites/slash/slash_api/security.robot
> +	[Documentation]		List of Test Covered
The documentation is not alligned.

2021-02-18 07:23 UTC, souravDgraph commented on test_suites/slash/slash_api/security.robot
> +	[Documentation]		List of Test Covered
Start "List of Test ... " from next line.

2021-02-18 07:23 UTC, souravDgraph commented on test_suites/slash/slash_api/security.robot
> +	[Documentation]		List of Test Covered
Same as above.

2021-02-18 07:23 UTC, souravDgraph commented on test_suites/slash/slash_api/org.robot
>  #    Remove Org From Deployment   Pokemon
Pokemon is icy-smoke

2021-02-18 07:23 UTC, souravDgraph commented on test_suites/slash/slash_api/security.robot
> +Documentation       This is a simple test with Robot Framework
This doc needs to be updated.

2021-02-18 07:23 UTC, souravDgraph commented on lib/slash_api_library/SlashAPI/keywords/organizations/organizations_keywords.py
> +        #Method to add a member to an organization with organization uid and member email id
After every '#' in comment give a space.

2021-02-18 07:23 UTC, souravDgraph commented on lib/slash_api_library/SlashAPI/components/models/organization/organization_model.py
> +    if(org_uid != None):
This could be better written.
```
variables = {}
if (org_uid != None):
    variables = {"id": org_uid}
query = GET_MEMBERS_IN_ORGANIZATION
```

2021-02-18 07:23 UTC, souravDgraph commented on lib/slash_api_library/SlashAPI/components/handlers/organizations/organizations_handler.py
> +        response = response.json()
This looks ambiguous.

2021-02-18 07:23 UTC, souravDgraph commented on lib/slash_api_library/SlashAPI/components/handlers/organizations/organizations_handler.py
> +            if response.json()["errors"][0]["message"] == expected_response_text:
Should'nt we log incase there is any other errors coming in? Will help in debugging.

2021-02-18 07:23 UTC, souravDgraph commented on lib/slash_api_library/SlashAPI/components/handlers/organizations/organizations_handler.py
> +        existing_org_res = self.connection.post_on_session(self.session_alias, appender,
Just check the indents here? Looks messy.

2021-02-18 07:40 UTC, SanthoshS22 commented on lib/slash_api_library/SlashAPI/components/models/organization/organization_model.py
> +    if(org_uid != None):
There are two queries present in it. GET_MEMBERS_IN_ORGANIZATION (to get all members from only one organization) and GET_MEMBERS_IN_ORGANIZATIONS (to get all members from all the organizations)

2021-02-24 05:58 UTC, vivetha-madesh commented on lib/slash_api_library/SlashAPI/components/handlers/deployments/deployments.py
> +    def get_deployment(session_alias, url, auth, deployment_id, expected_response_text="OK", expected_response=200):
rename this to get_deployment_with_deployment_id that will provide more context

2021-02-24 05:58 UTC, vivetha-madesh commented on lib/slash_api_library/SlashAPI/components/handlers/deployments/deployments.py
> +                raise Exception("Expected Body Response is not Found")
Expected error not found

2021-02-24 05:58 UTC, vivetha-madesh commented on lib/slash_api_library/SlashAPI/components/handlers/deployments/deployments.py
> +        if "errors" in response.json():
can we combine both the if statements in all the places

2021-02-24 05:58 UTC, vivetha-madesh commented on lib/slash_api_library/SlashAPI/components/handlers/organizations/organizations_handler.py
> +        response.json()["org_uid"] = org_uid
remove unused variable

2021-02-24 05:58 UTC, vivetha-madesh commented on lib/slash_api_library/SlashAPI/keywords/organizations/organizations_keywords.py
> +        response = self.org_handler.add_org_from_deployment(deployment_name, org_name)
any reason for this change involving a variable

2021-02-24 05:58 UTC, vivetha-madesh commented on test_suites/slash/slash_api/security.robot
> +${expected_response}	The organization is not found.
Rename variable appropriately

2021-02-24 05:58 UTC, vivetha-madesh commented on test_suites/slash/slash_api/security.robot
> +Only Owner View Members From Organization
Only Owner can view Members from organization
Test is not independent. Only if the above test executes this test can pass. 
Test cases need to be independent

2021-02-24 07:47 UTC, SanthoshS22 commented on lib/slash_api_library/SlashAPI/components/handlers/organizations/organizations_handler.py
> +        response.json()["org_uid"] = org_uid
This variable is required

2021-02-25 08:57 UTC, vivetha-madesh commented on lib/slash_api_library/SlashAPI/components/handlers/organizations/organizations_handler.py
> +        response.json()["org_uid"] = org_uid
can u point me to where it's getting used

2021-02-25 09:53 UTC, SanthoshS22 commented on lib/slash_api_library/SlashAPI/components/handlers/organizations/organizations_handler.py
> +        response.json()["org_uid"] = org_uid
test_suites/slash/slash_api/org.robot 
In Line no 25, this method is called
In Line no 28, I need org_uid to add a member to the organization

2021-02-26 09:10 UTC, kaushik691 commented
Is this branch still existing?

2021-02-26 16:26 UTC, SanthoshS22 commented
> Is this branch still existing?

Yes Krishna

2021-03-09 10:49 UTC, vivetha-madesh approved these changes

2021-03-10 04:21 UTC, souravDgraph approved these changes

2021-03-10 05:26 UTC, merged