Updated Live loader command
souravDgraph/Automation pull request #45
Opened 2021-02-15 10:31 UTC by kaushik691

Applying Fix for live loader issue

2021-02-16 15:41 UTC, souravDgraph requested changes

2021-02-16 15:41 UTC, souravDgraph commented on lib/dgraph_lib/Dgraph/components/setup_configurations.py
> +import io
are we using this ?

2021-02-16 15:41 UTC, souravDgraph commented on test_suites/dgraph/Linux/dgraph_suite_01.robot
> +#TC_04 Perform parallel live and bulk load on data
These TCs are commented?

2021-02-16 15:59 UTC, kaushik691 commented on test_suites/dgraph/Linux/dgraph_suite_01.robot
> +#TC_04 Perform parallel live and bulk load on data
I'll change

2021-02-16 16:01 UTC, kaushik691 commented on lib/dgraph_lib/Dgraph/components/setup_configurations.py
> +import io
No.. will update this

2021-02-17 04:54 UTC, souravDgraph approved these changes

2021-02-17 04:55 UTC, merged