Added Test Cases For Slash CLI
souravDgraph/Automation pull request #52
Opened 2021-02-25 14:19 UTC by SanthoshS22

2021-02-26 09:04 UTC, kaushik691 reviewed
Please address the review comments

2021-02-26 09:04 UTC, kaushik691 commented on lib/slash_cli_library/SlashCLI/keywords/organizations/organization_keywords.py
> +    def create_organization(environment, org_name, expected_return_code=0):
instead of passing environment always set it in this method (create_organization and reference it in all other methods)

2021-02-26 09:04 UTC, kaushik691 commented on lib/slash_cli_library/SlashCLI/keywords/organizations/organization_keywords.py
> +    def create_organization(environment, org_name, expected_return_code=0):
what do you think?

2021-02-26 09:04 UTC, kaushik691 commented on test_suites/slash/slash_cli/org.robot
> +
If you make the environment change in components you need to make changes here

2021-02-26 10:24 UTC, vivetha-madesh commented on lib/slash_cli_library/SlashCLI/keywords/organizations/organization_keywords.py
> +    def create_organization(environment, org_name, expected_return_code=0):
I think that will create a dependency between the keywords and removes flexibility

2021-03-02 04:43 UTC, vivetha-madesh reviewed
Pls pull the latest code once

2021-03-02 04:43 UTC, vivetha-madesh commented on lib/slash_cli_library/SlashCLI/components/deployments/deployments.py
> +                logger.info(type(key))
Is this logging really required in all the methods

2021-03-02 04:43 UTC, vivetha-madesh commented on lib/slash_cli_library/SlashCLI/components/organizations/organizations.py
> +    def get_organization_id(environment, org_name, expected_return_code=0):
A logic to address the duplicate organization name needs to be added

2021-03-02 04:43 UTC, vivetha-madesh commented on lib/slash_cli_library/SlashCLI/components/organizations/organizations.py
> +    def create_organization(environment, org_name, expected_return_code=0):
verify the message shown in cli for all the cases

2021-03-02 04:43 UTC, vivetha-madesh commented on test_suites/slash/slash_cli/org.robot
> +Variables           ../../../conf/slash/slash_api/variables.py
variables should point to cli variables not api

2021-03-02 04:43 UTC, vivetha-madesh commented on test_suites/slash/slash_cli/org.robot
> +${member_email}   krishna@dgraph.io
move these to the variables file

2021-03-02 05:49 UTC, SanthoshS22 commented on lib/slash_cli_library/SlashCLI/components/deployments/deployments.py
> +                logger.info(type(key))
Not required. I will remove it

2021-03-04 07:36 UTC, kaushik691 commented on lib/slash_cli_library/SlashCLI/components/deployments/deployments.py
> +                logger.info(type(key))
or you can change it to logger.debug()

2021-03-04 07:39 UTC, kaushik691 commented on lib/slash_cli_library/SlashCLI/keywords/organizations/organization_keywords.py
> +    def create_organization(environment, org_name, expected_return_code=0):
does the environment change for each keyword?

2021-03-04 10:20 UTC, SanthoshS22 commented on lib/slash_cli_library/SlashCLI/keywords/organizations/organization_keywords.py
> +    def create_organization(environment, org_name, expected_return_code=0):
No

2021-03-10 04:26 UTC, souravDgraph commented
@SanthoshS22 @kaushik691 @vivetha-madesh ca we review and merge this PR? Pending action for quite sometime.

2021-03-11 20:28 UTC, vivetha-madesh requested changes

2021-03-11 20:28 UTC, vivetha-madesh commented on lib/slash_cli_library/SlashCLI/components/organizations/organizations.py
> +                logger.info(organization)
Will this logic work if the organization name already exists

2021-03-16 09:50 UTC, merged