Modified docker code for live and bulk exection
souravDgraph/Automation pull request #56
Opened 2021-03-01 13:51 UTC by kaushik691

2021-03-02 16:43 UTC, souravDgraph requested changes
Requested some enhancements. 
Yaml files - Please get them once reviewed with @Sankalan13

2021-03-02 16:43 UTC, souravDgraph commented on .github/workflows/CI.yml
> +           export PATH=~/go/bin/:$PATH
make this change in other yamls also.

2021-03-02 16:43 UTC, souravDgraph commented on lib/dgraph_lib/Dgraph/components/setup_configurations.py
> +        else:
else not needed.
```
if ():
    // Do Something.
// Do otherthing
```

2021-03-02 16:43 UTC, souravDgraph commented on lib/dgraph_lib/Dgraph/components/setup_configurations.py
> +        if location:
Same as above

2021-03-02 16:43 UTC, souravDgraph commented on lib/dgraph_lib/Dgraph/components/setup_configurations.py
>              is_latest = is_latest_version
These Variable names are very confusing.

2021-03-02 16:43 UTC, souravDgraph commented on lib/dgraph_lib/Dgraph/components/setup_configurations.py
> +                          f"-f {rdf_file} -a {alpha_addr}:9080 -z {zero_addr}:5080 "
enhancement: We should also take the ports from the config files. This will be useful for read replica automation.

2021-03-02 16:43 UTC, souravDgraph commented on lib/dgraph_lib/Dgraph/components/setup_configurations.py
>              is_latest = is_latest_version
Variable name should be better.

2021-03-02 16:43 UTC, souravDgraph commented on utilities/create_docker_yml.py
>                                'ports': ["5080:5080", "6080:6080"],
port maps should be config driven.

2021-03-03 04:38 UTC, kaushik691 commented on .github/workflows/CI.yml
> +           export PATH=~/go/bin/:$PATH
okay

2021-03-03 04:39 UTC, kaushik691 commented on lib/dgraph_lib/Dgraph/components/setup_configurations.py
>              is_latest = is_latest_version
will look into it

2021-03-03 04:39 UTC, kaushik691 commented on lib/dgraph_lib/Dgraph/components/setup_configurations.py
> +                          f"-f {rdf_file} -a {alpha_addr}:9080 -z {zero_addr}:5080 "
okay

2021-03-03 04:40 UTC, kaushik691 commented on utilities/create_docker_yml.py
>                                'ports': ["5080:5080", "6080:6080"],
this will take some time

2021-03-03 04:40 UTC, kaushik691 commented on utilities/create_docker_yml.py
>                                'ports': ["5080:5080", "6080:6080"],
for now I have defaulted.. but we can look into these changes

2021-03-03 04:46 UTC, kaushik691 commented on lib/dgraph_lib/Dgraph/components/setup_configurations.py
> +        else:
else required to pick the location posting to local

2021-03-03 04:48 UTC, kaushik691 commented on lib/dgraph_lib/Dgraph/components/setup_configurations.py
> +        else:
yeah changed

2021-03-03 04:48 UTC, kaushik691 commented on lib/dgraph_lib/Dgraph/components/setup_configurations.py
> +        if location:
done

2021-03-03 17:01 UTC, souravDgraph approved these changes

2021-03-03 17:01 UTC, merged