Added Test Cases For Slash UI
souravDgraph/Automation pull request #71
Opened 2021-03-22 17:44 UTC by SanthoshS22

2021-03-24 09:46 UTC, vivetha-madesh requested changes
Remove all the sleeps in tests and handle them in selenium

2021-03-24 09:46 UTC, vivetha-madesh commented on lib/slash_ui_library/Slash/keywords/settings/settings_keywords.py
> +        time.sleep(10)
Avoid using sleep

2021-03-24 09:46 UTC, vivetha-madesh commented on lib/slash_ui_library/Slash/keywords/settings/settings_keywords.py
> +        browser.wait_until_page_contains_element(SettingsLocators.api.replace("%s", api_key_name), timeout=SettingsKeywords.timeout)
Api key name can be duplicate. Try to add a different logic

2021-03-24 09:46 UTC, vivetha-madesh commented on lib/slash_ui_library/Slash/locators/settings/settings.py
> +    delete_button = "xpath = //tbody//child::td[4]//button[text()='Delete']"
dont use indexes

2021-03-24 09:46 UTC, vivetha-madesh commented on lib/slash_ui_library/Slash/locators/settings/settings.py
> +    okay_button = "xpath = //div[@role='dialog']//div//button[text()='Okay']"
Any specific reason y we dint use //button[text()='Okay']

2021-03-24 09:46 UTC, vivetha-madesh commented on test_suites/slash/slash_ui/sanity.robot
> +    Delete Deployment     ${Browser_Alias}     ${BACKEND_NAME}
after clicking delete we have to validate whether the backend is deleted and not visible in UI

2021-03-24 09:46 UTC, vivetha-madesh commented on test_suites/slash/slash_ui/sanity.robot
> +    sleep     10
any reasons for this sleep

2021-03-24 09:46 UTC, vivetha-madesh commented on test_suites/slash/slash_ui/sanity.robot
> +    Click Api Explorer In Menu      ${Browser_Alias}
After clicking the menu we should validate whether it's landing on the corresponding pages correctly. In all the places

2021-03-24 09:46 UTC, vivetha-madesh commented on test_suites/slash/slash_ui/sanity.robot
> +    View Graphql Endpoint      ${Browser_Alias}      https://${BACKEND_NAME}.${BACKEND_ZONE}.aws.cloud.dgraph.io/graphql
This will be overridden if a subdomain is provided

2021-03-24 09:46 UTC, vivetha-madesh commented on test_suites/slash/slash_ui/sanity.robot
> +    [Setup]      Create Backend
Dont create a backend and delete it just to click a menu. Take them in suite setup

2021-03-24 09:46 UTC, vivetha-madesh commented on test_suites/slash/slash_ui/sanity.robot
> +    sleep    20
any specific reasons for 20 second sleep

2021-03-29 11:10 UTC, vivetha-madesh requested changes
Few comments from earlier review still needs to be addressed

2021-03-29 11:10 UTC, vivetha-madesh commented on test_suites/slash/slash_ui/sanity.robot
> +    Click General Tab      ${Browser_Alias}
Is this step required here

2021-03-29 11:10 UTC, vivetha-madesh commented on test_suites/slash/slash_ui/sanity.robot
> +    Click General Tab      ${Browser_Alias}
Is this step required here

2021-03-31 14:26 UTC, vivetha-madesh commented on lib/slash_ui_library/Slash/keywords/dashboard/dashboard_keywords.py
> +    def view_deployment_location(browser_alias, zone):
rename it to view_deployment_zone

2021-03-31 14:26 UTC, vivetha-madesh commented on lib/slash_ui_library/Slash/keywords/dashboard/dashboard_keywords.py
> +        browser.wait_until_page_does_not_contain_element(DashboardLocators.zone.replace("%s", 'Select Region'),
What are we trying to validate with the "select region" not in the zones dropdown

2021-03-31 14:29 UTC, vivetha-madesh requested changes

2021-03-31 15:33 UTC, SanthoshS22 commented on lib/slash_ui_library/Slash/keywords/dashboard/dashboard_keywords.py
> +    def view_cluster_usage_statistics(browser_alias):
cluster usage statistics will needs to be shown in the dashboard(bytes and no of queries)

2021-04-01 04:46 UTC, vivetha-madesh commented on lib/slash_ui_library/Slash/keywords/dashboard/dashboard_keywords.py
> +    def view_cluster_usage_statistics(browser_alias):
the statistics also include the values shown right that also needs to be validated.

2021-04-05 09:59 UTC, vivetha-madesh approved these changes

2021-04-06 10:40 UTC, merged