Jeager deployment option on create and update deployment
souravDgraph/Automation pull request #75
Opened 2021-04-01 06:04 UTC by vivetha-madesh

2021-04-05 09:05 UTC, kaushik691 requested changes

2021-04-05 09:05 UTC, kaushik691 commented on lib/slash_api_library/SlashAPI/components/handlers/deployments/deployments.py
> +                          jaegerTrace='0.01',
is it better to use **kwargs?

2021-04-05 09:05 UTC, kaushik691 commented on test_suites/slash/slash_api/dgraph_cloud.robot
> +    ...
docs missing

2021-04-05 09:05 UTC, kaushik691 commented on test_suites/slash/slash_api/super_admin.robot
> +    ...    - Update dgraph cloud deployment jaeger
docs missing

2021-04-05 09:48 UTC, vivetha-madesh commented on lib/slash_api_library/SlashAPI/components/handlers/deployments/deployments.py
> +                          jaegerTrace='0.01',
kwargs can be used but i want to explicitly call out so that no one misses these

2021-04-05 09:54 UTC, kaushik691 commented on lib/slash_api_library/SlashAPI/components/handlers/deployments/deployments.py
> +                          jaegerTrace='0.01',
okay

2021-04-05 09:55 UTC, kaushik691 approved these changes

2021-04-05 11:50 UTC, souravDgraph requested changes

2021-04-05 11:50 UTC, souravDgraph commented on lib/slash_api_library/SlashAPI/keywords/deployemnts/deployment_keywords.py
> +                          jaegerSize='0.5',
not sure on the default values plz double check.

2021-04-05 11:50 UTC, souravDgraph commented on test_suites/slash/slash_api/dgraph_cloud.robot
> +create Dgraph cloud deployment with default options
Better have one keyword doing all the things based n the parameter. Will avoid duplication of code.

2021-04-05 11:50 UTC, souravDgraph commented on test_suites/slash/slash_api/dgraph_cloud.robot
> +create Dgraph cloud deployment with default options
Goes same with all the keywords.

2021-04-06 06:31 UTC, vivetha-madesh commented on test_suites/slash/slash_api/dgraph_cloud.robot
> +create Dgraph cloud deployment with default options
the same keyword is used with different parameters. Here templating can be done but it will make it a single huge test case with different parameters but validation will become a bit complicated and logs debugging will become complex. 
So I avoided the templating.

2021-04-06 06:33 UTC, vivetha-madesh commented on lib/slash_api_library/SlashAPI/components/models/deployment/deployment.py
> +<<<<<<< HEAD
fixed it

2021-04-06 06:35 UTC, souravDgraph approved these changes

2021-04-06 07:47 UTC, merged