Added UI Test Cases - Phase 3
souravDgraph/Automation pull request #82
Opened 2021-04-09 10:06 UTC by SanthoshS22

2021-04-13 04:49 UTC, Sankalan13 commented on conf/slash/slash_api/variables.py
> +USER2_HEADER = { "Authorization" : "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjgwNzAiLCJleHAiOjE2MTcyMDk3MTAsImlzcyI6Imh0dHBzOi8vZGV2LWRncmFwaC1zYWFzLmF1dGgwLmNvbS8
Lets not add the bearer token like this, this is a security issue. We should add a reference to this name here and the token should reside as an environment variable in the machine it is running on.

2021-04-13 04:49 UTC, Sankalan13 commented on lib/slash_ui_library/Slash/locators/schema/schema.py
> +    add_type_button = "xpath = //button/following::div[text()='Add Type']"
Lets try to switch as many xpath selectors to css. It is a healthy habit to always use css selectors for locating elements.

2021-04-13 04:49 UTC, Sankalan13 commented on test_suites/slash/slash_ui/sanity.robot
> +${deployment_jwt_token}       eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJzL3Byb3h5IiwiZHVpZCI6IjB4Y2FkZmYyIiwiZXhwIjoxNjE3OTY0MTA0LCJpc3MiOiJzL2FwaSJ9.rtgNTm6ySN1RqnjE20i35QVaOuntfTXoiLe48cH_kVM
Why is this token hard coded here? Is this the user token of the jwt token of the backend? This would be subject to change and should be generated and added dynamically

2021-04-15 08:32 UTC, vivetha-madesh requested changes
Please add verifications to the tests wherever required

2021-04-15 08:32 UTC, vivetha-madesh commented on lib/slash_ui_library/Slash/locators/schema/schema.py
> +    edit_button = "xpath = //h3[text()='%s']/ancestor::div[1]//button[1]//*[local-name()='svg']"
Indexing is not a recommended practice. Tests will fail even if the surrounding element changes which will be create false alarms. 

this needs to be addressed everywhere

2021-04-15 08:32 UTC, vivetha-madesh commented on test_suites/slash/slash_ui/sanity.robot
> +    View Graphql Endpoint      ${Browser_Alias}      ${BACKEND_ZONE}.enterprise.stage.thegaas.com/graphql
This will fail if the deployment is created in aws or any other region

2021-04-15 08:32 UTC, vivetha-madesh commented on test_suites/slash/slash_ui/sanity.robot
> +    Add Field     ${Browser_Alias}       UntitledType0
can we try to use proper schema or type names

2021-04-15 08:32 UTC, vivetha-madesh commented on lib/slash_ui_library/Slash/keywords/schema/schema_keywords.py
> +    def validate_field_removed(browser_alias, field_name):
can the keyword name be more specific

2021-04-15 08:32 UTC, vivetha-madesh commented on lib/slash_ui_library/Slash/keywords/schema/schema_keywords.py
> +        browser.click_element(SchemaLocators.drop_all_data_button, timeout=SchemaKeywords.timeout)
are we expecting the button to be clicked twice ?

2021-04-15 08:32 UTC, vivetha-madesh commented on test_suites/slash/slash_ui/sanity.robot
> +    Deploy Schema      ${Browser_Alias}
after clicking deploy schema. are we verifying whether the schema is deployed and we are able to view the schema in UI

2021-04-15 08:32 UTC, vivetha-madesh commented on test_suites/slash/slash_ui/sanity.robot
> +    Deploy Schema      ${Browser_Alias}
after clicking deploy schema. are we verifying whether the schema is deployed and we are able to view the schema in UI

2021-04-15 08:32 UTC, vivetha-madesh commented on test_suites/slash/slash_ui/sanity.robot
> +    Click Settings In Menu     ${Browser_Alias}
Any specific reason y we navigate to settings page and come back to schema page

2021-04-15 08:32 UTC, vivetha-madesh commented on test_suites/slash/slash_ui/sanity.robot
> +    Click Create Backup Button       ${Browser_Alias}
are we verifying whether the backup is created after clicking backup button

2021-04-15 08:32 UTC, vivetha-madesh commented on test_suites/slash/slash_ui/sanity.robot
> +    Click Backups Tab      ${Browser_Alias}
Are we verifying whether the backups are listed on navigating to backup tab

2021-04-15 08:32 UTC, vivetha-madesh commented on lib/slash_ui_library/Slash/keywords/dashboard/dashboard_keywords.py
> +        browser.wait_until_page_contains_element(DashboardLocators.billing_label,
we have to verify the billing info and not just the label

2021-04-15 08:32 UTC, vivetha-madesh commented on test_suites/slash/slash_ui/sanity.robot
> +    Add Card     ${Browser_Alias}       4242424242424242      424      242      42424
dont hard code the card details in the test pls

2021-04-15 08:32 UTC, vivetha-madesh commented on test_suites/slash/slash_ui/sanity.robot
> +    Click Execute Query Button       ${Browser_Alias}
Are we verifying whether a mutation is going through and dumping data to the backend?

2021-04-15 08:32 UTC, vivetha-madesh commented on test_suites/slash/slash_ui/sanity.robot
> +    Click Execute Query Button       ${Browser_Alias}
Are we verifying whether a query is going through and fectching data from the backend?

2021-04-15 08:32 UTC, vivetha-madesh commented on test_suites/slash/slash_ui/sanity.robot
> +    Click Drop All Data Button      ${Browser_Alias}
after clicking drop data we need to verify whether the data is dropped

2021-04-22 06:54 UTC, vivetha-madesh reviewed
All the java scripts should be moved to locators file to reduce maintenance. 

We have to revisit and think of some ways to avoid indexes in locators and js

2021-04-22 06:54 UTC, vivetha-madesh commented on test_suites/slash/slash_ui/sanity.robot
> +    Verify Backup Created     ${Browser_Alias}     incremental     ${date_time}
A backup can be full or incremental

2021-04-22 06:54 UTC, vivetha-madesh commented on lib/slash_ui_library/Slash/keywords/settings/settings_keywords.py
> +        if(backups_list!=""):
Even if the backup details are shown wrong the test will pass

2021-04-22 06:54 UTC, vivetha-madesh commented on test_suites/slash/slash_ui/sanity.robot
> +Add Card And Verify Billing page
rename the test to "Add Card And Verify Billing page with 0$ bill"

2021-04-22 06:54 UTC, vivetha-madesh commented on lib/slash_ui_library/Slash/keywords/schema/schema_keywords.py
> +        browser.click_element(SchemaLocators.drop_all_data_button, timeout=SchemaKeywords.timeout)
any reason for this ?

2021-04-22 06:54 UTC, vivetha-madesh commented on test_suites/slash/slash_ui/sanity.robot
> +Should be able to run a mutation
Test is not independent. If the test is executed independently test will fail

2021-04-22 06:54 UTC, vivetha-madesh commented on test_suites/slash/slash_ui/sanity.robot
> +Should be able to query and return response
Test is not independent. If the test is executed independently test will fail

2021-04-22 07:20 UTC, SanthoshS22 commented on lib/slash_ui_library/Slash/keywords/schema/schema_keywords.py
> +        browser.click_element(SchemaLocators.drop_all_data_button, timeout=SchemaKeywords.timeout)
The button drop all data appears twice and needs to be clicked twice

2021-05-05 12:11 UTC, vivetha-madesh commented on lib/slash_ui_library/Slash/keywords/settings/settings_keywords.py
> +        if(backups_list!=""):
validating the backup details shown in UI is required

2021-05-05 12:11 UTC, vivetha-madesh commented on test_suites/slash/slash_ui/sanity.robot
> +    Verify Query Data      ${QUERY_RESULT1}      User
Verify the mutation response in Api explorer as well

2021-05-06 04:16 UTC, vivetha-madesh approved these changes

2021-05-06 04:16 UTC, vivetha-madesh commented on lib/slash_ui_library/Slash/keywords/api_explorer/api_explorer_keywords.py
> +        time.sleep(5)
pls remove sleeps

2021-05-06 05:41 UTC, SanthoshS22 commented on lib/slash_ui_library/Slash/keywords/api_explorer/api_explorer_keywords.py
> +        time.sleep(5)
Its required to get the data from the UI

2021-05-06 06:15 UTC, merged